apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-wiki-todo
  namespace: project
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: create-todo
              image: curlimages/curl:8.5.0
              env:
                - name: TODO_API
                  value: "http://todo-backend-svc:2346"
              command:
                - /bin/sh
                - -c
                - |
                  set -eu

                  WIKI_URL="$(curl -sL -o /dev/null -w '%{url_effective}' https://en.wikipedia.org/wiki/Special:Random)"

                  curl -sS -X POST "$TODO_API/todos" \
                    -H "Content-Type: application/json" \
                    -d "{\"todo\":\"Read ${WIKI_URL}\"}"
