apiVersion: ENC[AES256_GCM,data:oJU=,iv:FWTcIYR/D88Fpid6RoK+tmoyE53Njm3LdlhWildr6Xk=,tag:GBrA/ZBgOJ8YBL8NyGVvqw==,type:str]
kind: ENC[AES256_GCM,data:kXo8WNzJ,iv:lV9NonDyqiOa1Gbq9nk5T+fqOz+yFg5Lj4oHnUHkwhI=,tag:tMBxaaU+wUFrAJ4Dg51ToQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TXTnfDNqi8qLmnxih58g,iv:WO/QKrDoM0GE1tCt/h8Ph6DE+Rjoo3U8qRIGNk0v474=,tag:rDvPQwxglsTIFLKGkx6i2Q==,type:str]
    namespace: ENC[AES256_GCM,data:pmw+msokm55H,iv:pbQ8MSlq+iDIFdio/VkEPldGqealqEpW9b2NH8gTKTw=,tag:twHz7m7w+XoFJlLm9i7bCg==,type:str]
type: ENC[AES256_GCM,data:T1n5DJSo,iv:ASV8B6VNRnX8tVXoN5QdGiITNFzd79OfNXkNQa9eCTY=,tag:sw0tllJgAjjTpIHx3uI+sw==,type:str]
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:iZEfs+pMXSk=,iv:HcMtnk7RdQzUTuazu/PTk6LRegGNYjNHjVFA5t3/r3k=,tag:Ont+LzhdoZ/m00Xs0u2ZZA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:JOKCuGS+n1s=,iv:rA12OCza+6w765lipuOzXsp7Z4uOq5XLjsvhai/MYmI=,tag:tA5/y9MHnCl22CTlCo89iA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7xOZVi/9Sn1LPoO44RUUnA==,iv:kuRU9f8ctO8DirFbo/8822/hlMNKpsxlHXDqot9xwLI=,tag:zb4Ev7N+3A5odc7huY0Yuw==,type:str]
sops:
    age:
        - recipient: age1xenuqgfeetdrjj4egwgy8plfh5wvw0u7auckhkc4csryxsgp8p3sxrzg3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MVk4TEN3Lyt1TU9Ma2Vz
            ZXVvRWRYNGdyNTN6Skt0b25FcmVLRkphT2lFClJhdnU3djhuUmYwUzBoOWgxQVRU
            VUJZNEtmcEhSSHNHcS9Wc2FnNzBzbUEKLS0tIGlqSTZoQkVQeGZtb3pocVNQdDVl
            Mk9tdXRGNW5LZ2R1Q1NZZlJ2S2xGUjQKUYjXMGaEux1hPLazRUyrHqUMLnu3taJ4
            k1RWp9Z9XCs5rQiUzd7ozicAfhmDQh54E3mD6NCCulUeTQy9U273qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T22:16:47Z"
    mac: ENC[AES256_GCM,data:1VcxjEu+x3TuBxL6nGW2e/dcr7OyAX+e5yStxEcMmNPXcR3zxhTUXUOedXpi3khLK0dBWyir5Fp4pHpbB9I+quvcEBytb0wV6FTscPeRduvNzzQHRZgbdk3g7jlHGw0N/OYgCYnwCUKcTbmWbU58vH4hw7Oia5UaCIDHmDQ1uZc=,iv:Nlvf+coflLVQdjpqIq2ZqkoFaWCkAj8tTzHIs2dqh1U=,tag:WepiSm/pCqwxQ5nSDlXSSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
