apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-namespace-exercises
  namespace: exercises
spec:
  metrics:
    - name: cpu-usage-rate-sum
      initialDelay: 30s
      interval: 30s
      count: 10
      successCondition: result < 0.20
      failureCondition: result >= 0.20
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1768-prometheus.prometheus.svc.cluster.local:9090 
          query: |
            scalar(
                sum(rate(container_cpu_usage_seconds_total{namespace="exercises", container!="POD", image!=""}[5m]))
            )