apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-prod

resources:
  - ./../../base
  - ./../../manifests/cronjob-db-backup.yaml

patches:
  - path: broadcaster-patch.yaml
