apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project

resources:
  - postgres/postgres-statefulset.yaml
  - postgres/postgres-service.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
  - todo-app/manifests/configmap.yaml
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/service.yaml
  - todo-app/manifests/ingress.yaml
  - broadcaster/manifests/deployment.yaml