apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project

resources:
- postgres/postgres-statefulset.yaml
- postgres/postgres-service.yaml
- todo-backend/manifests/deployment.yaml
- todo-backend/manifests/service.yaml
- todo-app/manifests/configmap.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/service.yaml
- todo-app/manifests/ingress.yaml
- broadcaster/manifests/deployment.yaml

images:
- name: dazakharova/todo-app
  newTag: "2.0"
- name: dazakharova/todo-backend
  newTag: "1.9"
- name: dazakharova/todo-broadcaster
  newName: dazakharova/todo-broadcaster
  newTag: d2061b1dea13da50f8a60d610f7c5d92a68906ff
