apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-status
          emptyDir: {}
        - name: log-output-config
          configMap:
            name: log-output-configmap
      containers:
        - name: log-writer
          image: dazakharova/log_output:1.7
          command: [ "node", "writer.js" ]
          volumeMounts:
            - name: shared-status
              mountPath: /usr/src/app/shared
        - name: log-reader
          image: dazakharova/log_output:1.7
          volumeMounts:
            - name: shared-status
              mountPath: /usr/src/app/shared
            - name: log-output-config
              mountPath: /usr/src/app/config
              readOnly: true
          env:
            - name: PORT
              value: "3000"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE