apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-status
          emptyDir: {}
        - name: shared-status-volume
          persistentVolumeClaim:
            claimName: shared-status-claim
      containers:
        - name: log-writer
          image: dazakharova/log_output:1.4
          command: [ "node", "writer.js" ]
          volumeMounts:
            - name: shared-status
              mountPath: /usr/src/app/shared
        - name: log-reader
          image: dazakharova/log_output:1.4
          volumeMounts:
            - name: shared-status
              mountPath: /usr/src/app/shared
            - name: shared-status-volume
              mountPath: /usr/src/app/data
          env:
            - name: PORT
              value: "3000"