apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: random-image
          emptyDir: { }
      containers:
        - name: todo-app
          image: dazakharova/todo-app:1.8
          volumeMounts:
            - name: random-image
              mountPath: /usr/src/app/cache
          env:
            - name: PORT
              value: "5001"
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_URL
            - name: IMAGE_TTL_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_TTL_SECONDS
            - name: CACHE_DIR
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: CACHE_DIR
            - name: IMAGE_FILE_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: IMAGE_FILE_NAME
