apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/gateway.yaml
- manifests/route.yaml
images:
- name: dazakharova/log_output
  newName: dazakharova/log_output
  newTag: 032236fabb9ea64bc2ba22cb4cded5090f6301eb
