apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-server
  template:
    metadata:
      labels:
        app: todo-server
    spec:
      volumes:
        - name: random-image
          emptyDir: { }
      containers:
        - name: todo-server
          image: dazakharova/todo-app:1.6
          volumeMounts:
            - name: random-image
              mountPath: /usr/src/app/cache
          env:
            - name: PORT
              value: "5001"