apiVersion: v1
kind: Service
metadata:
  name: todo-server
spec:
  type: NodePort
  selector:
    app: todo-server
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 5001