name: Build and publish log-output application

on:
  push:
    branches: [ main ]
    paths:
      - 'log_output/**'
      - '.github/workflows/log-output.yaml'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push log-output image
        run: |
          docker build -t dazakharova/log_output:${GITHUB_SHA} ./log_output
          docker push dazakharova/log_output:${GITHUB_SHA}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image in kustomization
        run: |
          cd log_output
          kustomize edit set image PROJECT/IMAGE=dazakharova/log_output:${GITHUB_SHA}

      - name: Commit kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'log_output/kustomization.yaml'
          message: Release log-output ${{ github.sha }}
